apiVersion: serving.knative.dev/v1
kind: Service

metadata:
  name: manager

spec:
  template:
    spec:
      containers:
        - image: dasbd72/manager:python
          name: manager-container
          volumeMounts:
            - mountPath: /shared
              name: shared-volume
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
