apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-scale
spec:
  template:
    spec:
      containers:
        - image: docker.io/johnson684/image-scale:python
          name: image-scale
          volumeMounts:
            - mountPath: /shared
              name: shared-volume
          env:
            - name: MANAGER_URL
              value: tmp_manager_url
            - name: STORAGE_PATH
              value: /shared
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-recognition
spec:
  template:
    spec:
      containers:
        - image: docker.io/johnson684/image-recognition:python
          name: image-recognition
          volumeMounts:
            - mountPath: /shared
              name: shared-volume
          env:
            - name: MANAGER_URL
              value: tmp_manager_url
            - name: STORAGE_PATH
              value: /shared
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
