apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-scale
spec:
  template:
    spec:
      containers:
        - image: docker.io/johnson684/image-scale:python
          imagePullPolicy: Always
          name: image-scale
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: STORAGE_PATH
              value: /shared
            - name: LOG_LEVEL
              value: WARNING
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-recognition
spec:
  template:
    spec:
      containers:
        - image: docker.io/johnson684/image-recognition:python
          imagePullPolicy: Always
          name: image-recognition
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: STORAGE_PATH
              value: /shared
            - name: LOG_LEVEL
              value: INFO
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
