apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-scale
spec:
  template:
    spec:
      containers:

        - image: docker.io/johnson684/image-scale:python-socket
          imagePullPolicy: Always
          name: image-scale-socket
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: STORAGE_PATH
              value: /shared
            - name: LOG_LEVEL
              value: INFO
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-recognition
spec:
  template:
    spec:
      containers:

        - image: docker.io/johnson684/image-recognition:python-socket
          imagePullPolicy: Always
          name: image-recognition-socket

          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: STORAGE_PATH
              value: /shared
            - name: LOG_LEVEL
              value: INFO
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-watermark
spec:
  template:
    spec:
      containers:

        - image: docker.io/johnson684/image-watermark:python-socket
          imagePullPolicy: Always
          name: image-watermark-socket

          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: STORAGE_PATH
              value: /shared
            - name: LOG_LEVEL
              value: INFO
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim