apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-deleter
spec:
  schedule: "* * * * */1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cache-deleter
              image: johnson684/cache-deleter:python
              imagePullPolicy: Always
              volumeMounts:
                - name: shared-volume
                  mountPath: /shared
          restartPolicy: OnFailure
          volumes:
            - name: shared-volume
              persistentVolumeClaim:
                claimName: shared-volume-claim
