apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: manager-daemonset
  labels:
    app.kubernetes.io/name: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: manager-container
          image: johnson684/manager:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 40Mi
            limits:
              cpu: 300m
              memory: 400Mi
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: STORAGE_PATH
              value: /shared
            - name: ETCD_HOST
              value: "10.121.240.235"
      volumes:
        - name: shared-volume
          hostPath:
            path: /storage
