apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume-disk
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage-disk
    type: DirectoryOrCreate
